<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.1.1 (Python 3.13.0 on win32)" generated="2025-04-13T18:55:43.650150" rpa="false" schemaversion="5">
<suite id="s1" name="testApi marvel" source="C:\repositorio\apiteste\tests\testApi_marvel.robot">
<test id="s1-t1" name="ENDPOINT CHARACTERS - SUCESSO" line="7">
<kw name="DADO QUE EU CONSULTE O ENDPOINT" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:55:44.104460" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:55:44.104091" elapsed="0.000692"/>
</kw>
<status status="PASS" start="2025-04-13T18:55:44.102950" elapsed="0.001997"/>
</kw>
<kw name="QUANDO EU PASSAR OS PARAMETROS" owner="api_marvel">
<kw name="Create Dictionary" owner="BuiltIn">
<msg time="2025-04-13T18:55:44.106333" level="INFO">${headers} = {'content-type': 'application/json'}</msg>
<var>${headers}</var>
<arg>content-type=application/json</arg>
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<status status="PASS" start="2025-04-13T18:55:44.105873" elapsed="0.000514"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:55:52.871226" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460388AD0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:01.605837" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46036E710&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:10.552948" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46036E990&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:18.974762" level="FAIL">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46031C8A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<var>${resposta}</var>
<arg>marvel</arg>
<arg>/characters</arg>
<arg>params=apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2025-04-13T18:55:44.106584" elapsed="34.905000">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46031C8A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>${resposta.text}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-13T18:56:19.012376" elapsed="0.000106"/>
</kw>
<kw name="Set Test Variable" owner="BuiltIn">
<arg>${resposta}</arg>
<doc>Makes a variable available everywhere within the scope of the current test.</doc>
<status status="NOT RUN" start="2025-04-13T18:56:19.012963" elapsed="0.000089"/>
</kw>
<status status="FAIL" start="2025-04-13T18:55:44.105438" elapsed="34.908142">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46031C8A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="ENTÃO A API DEVE RETORNAR" owner="api_marvel">
<arg>200</arg>
<status status="NOT RUN" start="2025-04-13T18:56:19.014852" elapsed="0.000130"/>
</kw>
<status status="FAIL" start="2025-04-13T18:55:44.100248" elapsed="34.915874">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46031C8A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-t2" name="ENDPOINT CHARACTERS - APIKEY INVALIDA" line="12">
<kw name="DADO QUE EU CONSULTE O ENDPOINT" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:56:19.025280" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:56:19.024905" elapsed="0.000740"/>
</kw>
<status status="PASS" start="2025-04-13T18:56:19.024223" elapsed="0.001632"/>
</kw>
<kw name="QUANDO EU PASSAR OS PARAMETROS INVALIDOS" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:56:19.027449" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:56:19.027096" elapsed="0.000703"/>
</kw>
<kw name="Create Dictionary" owner="BuiltIn">
<msg time="2025-04-13T18:56:19.028471" level="INFO">${headers} = {'content-type': 'application/json'}</msg>
<var>${headers}</var>
<arg>content-type=application/json</arg>
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<status status="PASS" start="2025-04-13T18:56:19.028092" elapsed="0.000431"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:56:27.403286" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46031F5C0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:36.011329" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46032FE30&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:44.822447" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604309E0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:53.247339" level="FAIL">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460430D10&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<var>${resposta}</var>
<arg>marvel</arg>
<arg>/characters</arg>
<arg>params=apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</arg>
<arg>expected_status=any</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2025-04-13T18:56:19.028820" elapsed="34.242355">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460430D10&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>${resposta.text}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-13T18:56:53.271905" elapsed="0.000104"/>
</kw>
<kw name="Set Test Variable" owner="BuiltIn">
<arg>${resposta}</arg>
<doc>Makes a variable available everywhere within the scope of the current test.</doc>
<status status="NOT RUN" start="2025-04-13T18:56:53.272456" elapsed="0.000086"/>
</kw>
<status status="FAIL" start="2025-04-13T18:56:19.026459" elapsed="34.246547">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460430D10&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="ENTÃO A API DEVE RETORNAR" owner="api_marvel">
<arg>401</arg>
<status status="NOT RUN" start="2025-04-13T18:56:53.274238" elapsed="0.000128"/>
</kw>
<status status="FAIL" start="2025-04-13T18:56:19.022065" elapsed="34.253408">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460430D10&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-t3" name="CONSULTAR API CHARACTERS SEM USER KEY" line="17">
<kw name="DADO QUE EU CONSULTE O ENDPOINT" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:56:53.285665" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:56:53.284842" elapsed="0.001807"/>
</kw>
<status status="PASS" start="2025-04-13T18:56:53.283706" elapsed="0.003459"/>
</kw>
<kw name="QUANDO EU PASSAR PARAMETROS SEM USER KEY" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:56:53.290609" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:56:53.290038" elapsed="0.001069"/>
</kw>
<kw name="Create Dictionary" owner="BuiltIn">
<msg time="2025-04-13T18:56:53.291906" level="INFO">${headers} = {'content-type': 'application/json'}</msg>
<var>${headers}</var>
<arg>content-type=application/json</arg>
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<status status="PASS" start="2025-04-13T18:56:53.291457" elapsed="0.000522"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:57:01.688622" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460431BF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:10.310822" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432140&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:19.069244" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432470&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:27.508392" level="FAIL">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604327A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<var>${resposta}</var>
<arg>marvel</arg>
<arg>/characters</arg>
<arg>params=hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</arg>
<arg>expected_status=any</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2025-04-13T18:56:53.292445" elapsed="34.243426">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604327A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>${resposta.text}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-13T18:57:27.536459" elapsed="0.000059"/>
</kw>
<kw name="Set Test Variable" owner="BuiltIn">
<arg>${resposta}</arg>
<doc>Makes a variable available everywhere within the scope of the current test.</doc>
<status status="NOT RUN" start="2025-04-13T18:57:27.536761" elapsed="0.000045"/>
</kw>
<status status="FAIL" start="2025-04-13T18:56:53.288679" elapsed="34.248369">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604327A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="ENTÃO A API DEVE RETORNAR" owner="api_marvel">
<arg>409</arg>
<status status="NOT RUN" start="2025-04-13T18:57:27.537765" elapsed="0.000101"/>
</kw>
<status status="FAIL" start="2025-04-13T18:56:53.281598" elapsed="34.256842">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604327A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-t4" name="CONSULTAR API CHARACTERS COM HASH - VALIDO" line="22">
<kw name="DADO QUE EU CONSULTE O ENDPOINT" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:57:27.543251" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:57:27.542949" elapsed="0.000615"/>
</kw>
<status status="PASS" start="2025-04-13T18:57:27.542435" elapsed="0.001294"/>
</kw>
<kw name="QUANDO EU PASSAR PARAMETROS COM HASH VALIDO" owner="api_marvel">
<kw name="Create Dictionary" owner="BuiltIn">
<msg time="2025-04-13T18:57:27.545131" level="INFO">${headers} = {'content-type': 'application/json'}</msg>
<var>${headers}</var>
<arg>content-type=application/json</arg>
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<status status="PASS" start="2025-04-13T18:57:27.544776" elapsed="0.000416"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:57:35.967745" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433240&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:44.886237" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433570&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:53.701329" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604338A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:58:02.138066" level="FAIL">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030F460&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<var>${resposta}</var>
<arg>marvel</arg>
<arg>/characters</arg>
<arg>params=apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</arg>
<arg>expected_status=any</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2025-04-13T18:57:27.545423" elapsed="34.616227">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030F460&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>${resposta.text}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-13T18:58:02.162368" elapsed="0.000099"/>
</kw>
<kw name="Set Test Variable" owner="BuiltIn">
<arg>${resposta}</arg>
<doc>Makes a variable available everywhere within the scope of the current test.</doc>
<status status="NOT RUN" start="2025-04-13T18:58:02.162908" elapsed="0.000083"/>
</kw>
<status status="FAIL" start="2025-04-13T18:57:27.544298" elapsed="34.619129">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030F460&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="ENTÃO A API DEVE RETORNAR" owner="api_marvel">
<arg>200</arg>
<status status="NOT RUN" start="2025-04-13T18:58:02.164744" elapsed="0.000169"/>
</kw>
<status status="FAIL" start="2025-04-13T18:57:27.541418" elapsed="34.624577">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030F460&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-t5" name="CONSULTAR API CHARACTERS COM HASH - INVALIDO" line="28">
<kw name="DADO QUE EU CONSULTE O ENDPOINT" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:58:02.174074" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:58:02.173791" elapsed="0.000522"/>
</kw>
<status status="PASS" start="2025-04-13T18:58:02.173269" elapsed="0.001379"/>
</kw>
<kw name="QUANDO EU PASSAR PARAMETROS COM HASH INVALIDO" owner="api_marvel">
<kw name="Create Dictionary" owner="BuiltIn">
<msg time="2025-04-13T18:58:02.176168" level="INFO">${headers} = {'content-type': 'application/json'}</msg>
<var>${headers}</var>
<arg>content-type=application/json</arg>
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<status status="PASS" start="2025-04-13T18:58:02.175803" elapsed="0.000422"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:58:10.598413" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030E7A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1</msg>
<msg time="2025-04-13T18:58:19.238545" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030ECF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1</msg>
<msg time="2025-04-13T18:58:28.036918" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030F020&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1</msg>
<msg time="2025-04-13T18:58:36.467662" level="FAIL">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433020&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<var>${resposta}</var>
<arg>marvel</arg>
<arg>/characters</arg>
<arg>params=apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1</arg>
<arg>expected_status=any</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2025-04-13T18:58:02.176473" elapsed="34.315283">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433020&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>${resposta.text}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-13T18:58:36.492481" elapsed="0.000103"/>
</kw>
<kw name="Set Test Variable" owner="BuiltIn">
<arg>${resposta}</arg>
<doc>Makes a variable available everywhere within the scope of the current test.</doc>
<status status="NOT RUN" start="2025-04-13T18:58:36.493030" elapsed="0.000086"/>
</kw>
<status status="FAIL" start="2025-04-13T18:58:02.175247" elapsed="34.318302">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433020&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="ENTÃO A API DEVE RETORNAR" owner="api_marvel">
<arg>401</arg>
<status status="NOT RUN" start="2025-04-13T18:58:36.494765" elapsed="0.000127"/>
</kw>
<status status="FAIL" start="2025-04-13T18:58:02.171555" elapsed="34.324411">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433020&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-t6" name="CONSULTAR API CHARACTERS SEM O HASH" line="33">
<kw name="DADO QUE EU CONSULTE O ENDPOINT" owner="api_marvel">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:58:36.500874" level="INFO">Creating Session using : alias=marvel, url=http://gateway.marvel.com/v1/public, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>marvel</arg>
<arg>${url_marvel}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-04-13T18:58:36.500644" elapsed="0.000447"/>
</kw>
<status status="PASS" start="2025-04-13T18:58:36.500243" elapsed="0.000959"/>
</kw>
<kw name="QUANDO EU PASSAR PARAMETROS SEM O HASH" owner="api_marvel">
<kw name="Create Dictionary" owner="BuiltIn">
<msg time="2025-04-13T18:58:36.502154" level="INFO">${headers} = {'content-type': 'application/json'}</msg>
<var>${headers}</var>
<arg>content-type=application/json</arg>
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<status status="PASS" start="2025-04-13T18:58:36.501930" elapsed="0.000261"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2025-04-13T18:58:44.956984" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604327A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1</msg>
<msg time="2025-04-13T18:58:53.662331" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432690&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1</msg>
<msg time="2025-04-13T18:59:02.494654" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432250&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1</msg>
<msg time="2025-04-13T18:59:18.260677" level="FAIL">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460431480&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<var>${resposta}</var>
<arg>marvel</arg>
<arg>/characters</arg>
<arg>params=apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1</arg>
<arg>expected_status=any</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2025-04-13T18:58:36.502335" elapsed="41.782098">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460431480&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>${resposta.text}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-13T18:59:18.285121" elapsed="0.000055"/>
</kw>
<kw name="Set Test Variable" owner="BuiltIn">
<arg>${resposta}</arg>
<doc>Makes a variable available everywhere within the scope of the current test.</doc>
<status status="NOT RUN" start="2025-04-13T18:59:18.285394" elapsed="0.000041"/>
</kw>
<status status="FAIL" start="2025-04-13T18:58:36.501615" elapsed="41.784037">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460431480&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="ENTÃO A API DEVE RETORNAR" owner="api_marvel">
<arg>409</arg>
<status status="NOT RUN" start="2025-04-13T18:59:18.286303" elapsed="0.000091"/>
</kw>
<status status="FAIL" start="2025-04-13T18:58:36.499453" elapsed="41.787424">ConnectionError: HTTPConnectionPool(host='gateway.marvel.com', port=80): Max retries exceeded with url: /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460431480&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<status status="FAIL" start="2025-04-13T18:55:43.652049" elapsed="214.637482"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="6" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="6" skip="0" id="s1" name="testApi marvel">testApi marvel</stat>
</suite>
</statistics>
<errors>
<msg time="2025-04-13T18:55:52.871226" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460388AD0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:01.605837" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46036E710&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:10.552948" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46036E990&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:27.403286" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46031F5C0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:36.011329" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46032FE30&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:56:44.822447" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604309E0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:01.688622" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460431BF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:10.310822" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432140&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:19.069244" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432470&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:35.967745" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433240&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:44.886237" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460433570&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:57:53.701329" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604338A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b45&amp;ts=1</msg>
<msg time="2025-04-13T18:58:10.598413" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030E7A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1</msg>
<msg time="2025-04-13T18:58:19.238545" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030ECF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1</msg>
<msg time="2025-04-13T18:58:28.036918" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A46030F020&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;hash=b64a96ba9ce4c7f665a29d3e3cbd7b4&amp;ts=1</msg>
<msg time="2025-04-13T18:58:44.956984" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A4604327A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1</msg>
<msg time="2025-04-13T18:58:53.662331" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432690&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1</msg>
<msg time="2025-04-13T18:59:02.494654" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001A460432250&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /v1/public/characters?apikey=54404ddf7bcb1f389cf00f7c78a83c1b&amp;ts=1</msg>
</errors>
</robot>
